### ISSUE TITLE
How to start webdriver-manager

### ISSUE THREAD

**Issue by DannyMoerkerke** [jciolek/docker-protractor-headless#12]
When starting the container with:
`docker run -it --privileged --rm --net=host -v /dev/shm:/dev/shm -v $(pwd):/protractor webnicer/protractor-headless $@`

I get the following error:
`Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444`

probably because webdriver-manager is not running.
How should I use this?

**Comment by jciolek** [comment]
In essence, you shouldn't need to start the Selenium server while running your tests locally. Running the tests with `directConnect` is supposed to be faster.

I presume your protractor config has the following setting:
seleniumAddress: 'http://127.0.0.1:4444/wd/hub'

If you remove that then everything should start working.

**Comment by DannyMoerkerke** [comment]
Yes that works. My tests now all fail since none of the elements are found but that is an entirely different problem that I should investigate.
Thanks!

**Comment by jciolek** [comment]
I'm glad it worked! Thanks for your reply. I'm closing this issue.
