### ISSUE TITLE
Running multiple docker instances simultaneously

### ISSUE THREAD

**Issue by w4pp** [jciolek/docker-protractor-headless#19]
Is not possible at the moment because the following xfvb error:
`xvfb-run: error: Xvfb failed to start`

I found the problem is resolved by removing the locks before running xfvb-run in protractor.sh:
`rm -f /tmp/.X*lock`

Any chance you could add this?

Thnx

**Comment by jciolek** [comment]
Hi @w4pp 

Thanks for bringing up this issue.

I have added flag `-a` to xvfb which fixes the problem. It's in commit [4c25f1](https://github.com/jciolek/docker-protractor-headless/commit/4c25f1f0202c0dda4852f12c636267926229da5b)
