### ISSUE TITLE
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444

### ISSUE THREAD

**Issue by animulli** [jciolek/docker-protractor-headless#2]
Hi jciolek,

I've been trying to setup a practice run on my OSX with the image using this command:

docker run -it --privileged --rm --net=host -v $(pwd):/protractor webnicer/protractor-headless conf.js

but get the following error, no ideas?

Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444

My conf.js file does have this defined in the exports.config "seleniumAddress: 'http://localhost:4444/wd/hub'," removing this gets me another error

Error: Timed out waiting for the WebDriver server at http://10.0.2.15:48041/wd/hub

**Comment by animulli** [comment]
nvm...works sorry.

**Comment by Pablodotnet** [comment]
What was the problem @animulli ?? I'm with the same issue

**Comment by jciolek** [comment]
@Pablodotnet did you remove `seleniumAddress` from your Protractor config?

**Comment by ajitqait** [comment]
I am running protractor script using docker-compose with setup of selenium grid and calling dockerfile in docker-compose using build: .
Docker Compose File Is below:

version: '3'

services:
    progrid:
        image: selenium/hub:3.141.59-20210105
        container_name: progrid
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=240000
            - GRID_BROWSER_TIMEOUT=240000
        networks:
            - progrid_grid_internal

    nodechrome:
        image: selenium/node-chrome-debug:3.141.59-20210105
        depends_on:
            - progrid
        environment:
            - HUB_HOST=progrid
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=1
            - NODE_MAX_SESSION=2
        networks:
            - progrid_grid_internal
    first:
        build: .
        depends_on:
            - nodechrome
        environment:
            - HUB_HOST=progrid
            - BROWSER=chrome
networks:
    progrid_grid_internal:


Dockerfile:

FROM node:alpine

RUN mkdir /DLT_Labs

WORKDIR /DLT_Labs/

RUN apk update && apk add bash 
  

RUN npm install -g protractor@5.4.4
# RUN webdriver-manager update
RUN npm install
COPY ./ ./

CMD protractor proconf.js

proconf.js
exports.config = {
  framework: 'jasmine',
  capabilities: {
    'browserName': 'chrome'
  },
  seleniumAddress: 'http://progrid:4444/wd/hub',
  specs: ['spec.js']
}

spec.js:

describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');
    
    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

Error:
Getting two type of error : 
 E/launcher - Error: EAI_AGAIN getaddrinfo EAI_AGAIN progrid

Or EConnectRefused:127.0.0.0:4444


Please help me out for this problem.
