### ISSUE TITLE
Error: chrome not reachable

### ISSUE THREAD

**Issue by Izhaki** [jciolek/docker-protractor-headless#30]
We are getting a "chrome not reachable" error when running the container.

This is solve by providing chrome with `--no-sandbox` argument. Like so in Protractor:

```javascript
capabilities: {
  browserName: 'chrome',
  chromeOptions: {
    args: ['--no-sandbox'],
  },
},
```

Best details I've found on this are [here](https://github.com/elgalu/docker-selenium#chrome-not-reachable-or-timeout-after-60-secs):

> In CentOS and apparently since docker 1.10.0 is necessary to disable sandbox mode through --no-sandbox example client implementation.

Note that on that repo, they just set an environment variable on the Dockerfile:

    CHROME_ARGS="--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-infobars" \

**Comment by jciolek** [comment]
Hey Izhaki,

Thanks for bringing that issue to my attention. Which version of the image have you been using?

Cheers,
Jacek

**Comment by Izhaki** [comment]
We've just used

    $ docker pull webnicer/protractor-headless

So I reckon it's the latest?

**Comment by MrSaints** [comment]
@Izhaki It's a known issue when it comes to running Chrome in Docker. SUID does a lot of things, and requires additional permissions to sandbox Flash for example. That is why running it [Docker] with the `--privileged` flag is also a solution (likewise with `--security-opt seccomp=unconfined`). But it is generally easier to just execute Chrome with `--no-sandbox`.

**Comment by gilShin** [comment]
Not sure I understand where should I pass the --no-sandbox flag in the command.
Can someone please add an example?

**Comment by gilShin** [comment]
If I understood correctly, I have added the following command line argument:
-e CHROME_ARGS="--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-infobars"

Still getting "E/launcher - chrome not reachable"

Just want to add that I'm running the protractor from withing a docker image that supports docker in docker. Maybe this is my issue.

**Comment by Izhaki** [comment]
@gilShin Where do you set this?

This works for us (`protractor_conf.js`):

```
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        // Required to launch chrome in a docker container. `docker run --privileged` doesn't seem to work so we using `--no-sandbox` instead.
        '--no-sandbox',

        // See https://github.com/angular/protractor/blob/299fc8d96b3e5daf632a1c584728214ababcebf8/docs/browser-setup.md#using-headless-chrome
        '--disable-gpu'
      ]
    },
  }
```

**Comment by gilShin** [comment]
OK
I'm a devop and not familiar with protractor_conf.js syntax. May protractor_conf.js file looks something like that:
`var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');

exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  suites: {
    smoke: './**/nkDeploy.e2e.js',

    regression: ['./**/nkCreateNsd.e2e.js','./**/nkCreateResource.e2e.js','./**/nkCatalogList.e2e.js','./**/nkResourceVIM.e2e.js','./**/nkResourceVNFM.e2e.js','./**/nkResourceSDN.e2e.js', './**/nkAbout.e2e.js']
  },
  directConnect: true,
  framework: 'jasmine2',
  params: {
    url: 'https://localhost:3000/'
  },
  allScriptsTimeout: 1800000,
  getPageTimeout: 1800000,
  onPrepare: function() {
    jasmine.getEnv().addReporter(
      new Jasmine2HtmlReporter({
        savePath: './test/reports/',
        takeScreenshots: true,
        screenshotsFolder: 'images',
        takeScreenshotsOnlyOnFailures: true,
        fixedScreenshotName: true,
        consolidateAll: true
      })
    );
    var jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
      consolidateAll: true,
      savePath: 'testresults',
      filePrefix: 'xmloutput'
    }));

    // Disable animations so e2e tests run more quickly
    var disableNgAnimate = function() {
      angular.module('disableNgAnimate', []).run(['$animate', function($animate) {
        $animate.enabled(false);
      }]);
    };

    browser.addMockModule('disableNgAnimate', disableNgAnimate);
    console.log("Protractor animation is disabled");

    browser.driver.manage().window().maximize();

  }
};`

Where can I add the capabilities?

Thanks

**Comment by Izhaki** [comment]
`capabilities` is a root property in the config.

See example: https://github.com/angular/protractor/blob/master/docs/api-overview.md#example-config-file

**Comment by gilShin** [comment]
@Izhaki That worked like a charm

Thanks a lot!

**Comment by Izhaki** [comment]
We don't have this issue any longer, so closing.
