### ISSUE TITLE
/dev/shm does not apply on a Mac.

### ISSUE THREAD

**Issue by Izhaki** [jciolek/docker-protractor-headless#34]
Based on [this](https://stackoverflow.com/questions/2033362/does-os-x-have-an-equivalent-to-dev-shm), there is no equivalent to `/dev/shm` on a Mac.

Per the README, it seems that `--shm-size` has [long been implemented](https://github.com/moby/moby/issues/2606).

Perhaps it is worth updating the README?

**Comment by jciolek** [comment]
Absolutely. Updated README with cb909fb9c91bed280bbcf2b5ed53f43d592ec238
