### ISSUE TITLE
WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0

### ISSUE THREAD

**Issue by songokudbz** [jciolek/docker-protractor-headless#7]
Using latest google Chrome Version 54.0.2840.71 m and the latest Chrome drivers 2.24(https://sites.google.com/a/chromium.org/chromedriver/downloads) I get the following error: 

`
12:59:39 [chrome #01-0] WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0
12:59:39 [chrome #01-0]   (Driver info: chromedriver=2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3),platform=Linux 4.4.0-42-generic x86_64)
12:59:39 [chrome #01-0]     at WebDriverError (/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
12:59:39 [chrome #01-0]     at Object.checkLegacyResponse (/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
12:59:39 [chrome #01-0]     at parseHttpResponse (/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
12:59:39 [chrome #01-0]     at client_.send.then.response (/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
12:59:39 [chrome #01-0]     at ManagedPromise.invokeCallback_ (/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
12:59:39 [chrome #01-0]     at TaskQueue.execute_ (/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
12:59:39 [chrome #01-0]     at TaskQueue.executeNext_ (/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
12:59:39 [chrome #01-0]     at asyncRun (/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
12:59:39 [chrome #01-0]     at /protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
12:59:39 [chrome #01-0]     at process._tickCallback (internal/process/next_tick.js:103:7)
12:59:39 [chrome #01-0] From: Task: WebDriver.createSession()
12:59:39 [chrome #01-0]     at Function.createSession (/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
12:59:39 [chrome #01-0]     at Driver (/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
12:59:39 [chrome #01-0]     at Direct.getNewDriver (/protractor/node_modules/protractor/built/driverProviders/direct.js:68:26)
12:59:39 [chrome #01-0]     at Runner.createBrowser (/protractor/node_modules/protractor/built/runner.js:198:43)
12:59:39 [chrome #01-0]     at /protractor/node_modules/protractor/built/runner.js:277:30
12:59:39 [chrome #01-0]     at _fulfilled (/protractor/node_modules/q/q.js:834:54)
12:59:39 [chrome #01-0]     at self.promiseDispatch.done (/protractor/node_modules/q/q.js:863:30)
12:59:39 [chrome #01-0]     at Promise.promise.promiseDispatch (/protractor/node_modules/q/q.js:796:13)
12:59:39 [chrome #01-0]     at /protractor/node_modules/q/q.js:556:49
12:59:39 [chrome #01-0]     at runSingle (/protractor/node_modules/q/q.js:137:13)
`

Please update the chrome browser from your image to version 54.

**Comment by jciolek** [comment]
Hi @songokudbz,

Thanks for using my image and sorry for the delay in answering.

So far there was no control over which version of chrome was being used other then it was supposed to be the latest available. I have pinned down versions of webdriver, chrome, protractor, node, the first two having seemed to make most trouble because of incompatibility.

Please see my comment at #10 

I am closing this issue for now, as it should be resolved.
